version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    ports:
      - 5432:5432

  api:
    image: turbo-prisma-ex
    build:
      args:
        - DATABASE_URL="DATABASE_URL="postgresql://dev:dev@postgres:5432/logs?schema=public""
    command: pnpm dev:api
    ports:
      - 4000:4000
      - 9090:9090 # for debugging metrics
    volumes: &mounted # speed up development by mounting some local directories with hot reload
      - ./apps/api/src:/app/apps/api/src
